Task/um 720 dev doc for configuring leak sanitizer
LLNL/Umpire pull request #470
Opened 2020-10-07 21:40 UTC by kab163

2020-10-07 21:41 UTC, kab163 commented
LGTM

2020-10-07 21:45 UTC, kab163 commented
LGTM

2020-10-07 23:03 UTC, kab163 commented
LGTM

2020-10-08 16:20 UTC, davidbeckingsale requested changes
Just one quick change. This looks great, thank you!

2020-10-08 16:20 UTC, davidbeckingsale commented on docs/sphinx/developer_guide.rst
> +.. note::
🎉

2020-10-08 16:20 UTC, davidbeckingsale commented on docs/sphinx/developer_guide.rst
> +This will configure a build with Clang 9.0.0 and the Leak Sanitizer. If there is a leak in one of the tests, it can be useful to gather more information about what happened and more details about whe
Could you add a note saying that the CMake file `hc-quartz-....` can be re-used?

2020-10-08 16:55 UTC, kab163 commented
LGTM

2020-10-08 16:57 UTC, mcfadden8 approved these changes
Looks great to me!

2020-10-08 17:16 UTC, kab163 commented
LGTM

2020-10-08 18:11 UTC, davidbeckingsale approved these changes

2020-10-08 18:14 UTC, merged