Bugfix/um 703 mpi for ci
LLNL/Umpire pull request #478
Opened 2020-10-21 22:16 UTC by mcfadden8

2020-10-21 22:20 UTC, mcfadden8 commented
LGTM

2020-10-26 22:55 UTC, davidbeckingsale requested changes
Couple of quick changes. Also, is the radiuss-spack-config submodule pointing at a branch?

2020-10-26 22:55 UTC, davidbeckingsale commented on cmake/UmpireMacros.cmake
> +      # The 'CONFIGURATIONS Benchmark' line excludes benchmarks
I don't think this comment should be here.

2020-10-26 22:55 UTC, davidbeckingsale commented on CHANGELOG.md
> +- Added gitlab testing of Umpire when MPI is enabled
```suggestion
- Added GitLab testing of Umpire when MPI is enabled
```

2020-10-26 22:55 UTC, davidbeckingsale commented on tests/integration/io/CMakeLists.txt
> +      NAME io_tests_1
Can the names be more descriptive than _1, _2 please?

2020-10-27 00:04 UTC, mcfadden8 commented
LGTM

2020-10-27 15:59 UTC, davidbeckingsale requested changes
Can you point the submodule at the latest "main" - the PR with MPI configs was merged.

2020-10-27 16:11 UTC, davidbeckingsale approved these changes

2020-10-27 16:11 UTC, mcfadden8 commented
LGTM

2020-10-27 17:47 UTC, merged