Story/um 767 get allocator docs
LLNL/Umpire pull request #509
Opened 2020-12-09 22:49 UTC by kab163

- [ ] Readability of documentation fulfills the purpose of JIRA ticket?
- [ ] Is it sufficient to have examples I have currently in PR or should there be a different kind of example?

2020-12-09 22:50 UTC, kab163 commented
LGTM

2020-12-10 18:12 UTC, kab163 commented
LGTM

2020-12-10 18:38 UTC, kab163 commented
LGTM

2020-12-10 22:56 UTC, kab163 commented
LGTM

2020-12-15 16:58 UTC, kab163 commented
Resulting ReadTheDocs pages:
https://umpire.readthedocs.io/en/story-um-767-getallocator-docs/tutorial/dynamic_pool.html
https://umpire.readthedocs.io/en/story-um-767-getallocator-docs/tutorial/allocators.html

2020-12-15 16:59 UTC, kab163 commented
LGTM

2020-12-15 18:29 UTC, kab163 commented
LGTM

2020-12-15 20:44 UTC, kab163 commented
LGTM

2020-12-15 21:59 UTC, mcfadden8 approved these changes
Looks great to me.  Thanks!

2020-12-15 22:43 UTC, kab163 commented
LGTM for the win

2020-12-15 22:43 UTC, davidbeckingsale requested changes
One suggestion. I also think that we could say `build a new allocator from` instead of saying `off of`. I think the former is clearer.

2020-12-15 22:43 UTC, davidbeckingsale commented on docs/sphinx/tutorial/allocators.rst
> +This "add-on" allocator will also be built with the same memory resource. More information
```suggestion
This new allocator will also be built with the same memory resource. More information
```

2020-12-15 23:19 UTC, kab163 commented
LGTM

2020-12-15 23:59 UTC, kab163 commented
LGTM

2020-12-16 18:53 UTC, kab163 commented
LGTM

2020-12-16 19:49 UTC, davidbeckingsale commented
LGTM

2020-12-16 19:49 UTC, davidbeckingsale approved these changes

2020-12-16 20:31 UTC, merged