Feature/um 836 replay per allocator statistics
LLNL/Umpire pull request #544
Opened 2021-03-02 01:12 UTC by mcfadden8

Replay will now display the following statistics when requested:
```
$ ../install/bin/replay -i umpire.130469.0.replay --stats-on-release
Filename                                Allocator                               Current Size    Actual Size     High Watermark
umpire.130469.0.replay                  UM_object_pool                          18432           524288000       0
umpire.130469.0.replay                  UM_pool_temps                           0               778558976       676982088
umpire.130469.0.replay                  preferred_location_device               16884687360     16884687360     16884692480
umpire.130469.0.replay                  UM                                      17408975376     17408975376     17408980496
umpire.130469.0.replay                  __umpire_internal_0_byte_pool           0               2113            0
umpire.130469.0.replay                  UM_pool                                 8080938944      16106127360     13541160960
umpire.130469.0.replay                  __umpire_internal_null                  0               0               0

UM_pool:
    Largest Allocation: 760569040
    [2^2 - 2^3) = 1
    [2^4 - 2^5) = 1
    [2^7 - 2^8) = 9
    [2^8 - 2^9) = 2
    [2^9 - 2^10) = 4
    [2^10 - 2^11) = 6
    [2^11 - 2^12) = 16
    [2^12 - 2^13) = 10
    [2^18 - 2^19) = 8
    [2^19 - 2^20) = 4
    [2^20 - 2^21) = 15
    [2^21 - 2^22) = 3
    [2^22 - 2^23) = 6
    [2^23 - 2^24) = 15
    [2^24 - 2^25) = 40
    [2^25 - 2^26) = 13
    [2^26 - 2^27) = 61
    [2^27 - 2^28) = 2
    [2^28 - 2^29) = 16
    [2^29 - 2^30) = 2

UM_pool_temps:
    Largest Allocation: 122473944
    [2^16 - 2^17) = 1
    [2^19 - 2^20) = 5
    [2^21 - 2^22) = 5
    [2^22 - 2^23) = 1
    [2^23 - 2^24) = 4
    [2^24 - 2^25) = 4
    [2^26 - 2^27) = 4

UM_object_pool:
    Largest Allocation: 184
    [2^7 - 2^8) = 96
```

2021-03-02 01:12 UTC, mcfadden8 commented
LGTM

2021-03-02 14:58 UTC, mcfadden8 commented
LGTM

2021-03-02 15:07 UTC, mcfadden8 commented
LGTM

2021-03-02 19:57 UTC, mcfadden8 commented
LGTM

2021-03-03 02:58 UTC, mcfadden8 commented
LGTM

2021-03-03 15:16 UTC, mcfadden8 commented
Good morning @davidbeckingsale, please let me know if there is anything else you would like to see in this PR.  Otherwise, I think it is ready.

Thanks,

2021-03-03 17:20 UTC, davidbeckingsale requested changes

2021-03-03 17:20 UTC, davidbeckingsale commented on tools/replay/replay.cpp
> +      "Display pool allocaiton size statistics");
```suggestion
      "Display pool allocation size statistics");
```

2021-03-03 17:24 UTC, mcfadden8 commented
LGTM

2021-03-03 17:51 UTC, davidbeckingsale approved these changes
🙏

2021-03-03 17:54 UTC, merged