Add a DeviceAllocator reset function
LLNL/Umpire pull request #650
Opened 2021-09-16 20:21 UTC by kab163

2021-09-17 22:27 UTC, davidbeckingsale approved these changes, later dismissed

2021-09-20 17:10 UTC, davidbeckingsale requested changes
I think we ought to have a test or example that uses this function, both on the host, and on the device.

2021-09-20 18:24 UTC, kab163 commented
> I think we ought to have a test or example that uses this function, both on the host, and on the device.

I added an example of calling the reset function on the host. I think it'd be better to hold off on the device until I come up with a more useful example. (Right now, it would look the exact same as the host call since I'm only using one thread to do the DA stuff on the GPU.) What do you think?

2021-09-20 20:29 UTC, davidbeckingsale approved these changes

2021-09-20 20:31 UTC, merged