cmake: properly add Fortran module directories
LLNL/Umpire pull request #783
Opened 2022-09-12 16:13 UTC by germasch

The fix in the INSTALL_INTERFACE is necessary so that a project that does

```
find_package(umpire)

[...]
target_link_libraries(my_fortran_exe PRIVATE umpire)
```

actually will find the `umpire_mod.mod` file, which gets installed into `include/umpire/`.

The change in the BUILD_INTERFACE is for the case where umpire is used in another cmake project via `add_subdirectory()`, which is probably not an offically supported case, but it can be quite useful.

2022-10-10 18:12 UTC, davidbeckingsale requested changes

2022-10-10 18:12 UTC, davidbeckingsale commented on src/umpire/interface/c_fortran/CMakeLists.txt
> +  $<INSTALL_INTERFACE:include/umpire> # for Fortran module files
Can this be modified using a language expression so it's only used for Fortran?

2022-10-10 19:23 UTC, germasch commented on src/umpire/interface/c_fortran/CMakeLists.txt
> +  $<INSTALL_INTERFACE:include/umpire> # for Fortran module files
Sure, good point. I added a commit to protect those include dirs for `$<COMPILE_LANGUAGE:Fortran>` and also rebased.

2022-10-11 15:50 UTC, mcfadden8 approved these changes
Thanks @germasch - These changes seem reasonable to me.

2022-10-11 15:54 UTC, merged