Add SyncBeforeFree strategy
LLNL/Umpire pull request #821
Opened 2023-04-17 20:48 UTC by davidbeckingsale

2023-05-03 22:15 UTC, MrBurmark submitted a review, later dismissed

2023-05-08 16:43 UTC, mcfadden8 requested changes
For testing, I think it would be good to have a test (that could also serve as an example), that simply creates an allocator of this kind and uses it for a couple of allocations and deallocations.  This would be a minimum test to make sure that everything links up and the calls all successfully pass through without error.

2023-06-01 16:01 UTC, MrBurmark commented on src/umpire/event/event.hpp
> +inline std::string to_string(camp::resources::Resource& r)
We should fix the constness of get_platform in camp.

2024-06-13 20:35 UTC, davidbeckingsale commented
Will be superseded by other features.

2024-06-13 20:35 UTC, closed without merging